version: "3.7"

services:
  redis:
    container_name: standalone-redis
    image: redis:6.2.6
    ports:
      - 6379:6379
    restart: always
    command: redis-server /usr/local/conf/redis.conf
    volumes:
      - ./conf/redis.conf:/usr/local/conf/redis.conf